### ISSUE TITLE
Augment Expanding - Quantile (Polars Engine): More Elegant/Scalable Way of Handling Parameters

### ISSUE THREAD

**Issue by mdancho84** [business-science/pytimetk#115]
I suggest we come up with a more elegant solution that the "quantile" parameter. 

I can see us adding more functions that have parameters down the road and adding parameters to the augment_expanding function isn't scalable. 

One thought I had is allowing users to add polars functions like we do lambda functions with pandas as Tuples.

**Comment by alexriggio** [comment]
So these polars functions would throw an error if the engine was not set to 'polars'?

Something like this?

`( 'quantile', rolling_quantile(quantile=0.75, window_size=<dataframe_length>, min_periods=1, interpolation='midpoint') )`

The current implementation operates only with `rolling_` functions in this manner `df.group_by(group_names).agg(rolling_agg_function)`. May need to find a more flexible solution of the form `df.group_by_rolling.agg(agg_function)`.

Right now series-based lambda functions will work with the polars backend through `rolling_apply`, albeit they are slower than pandas, which could be do to an inefficient implementation at the moment.

Haven't tried to implement a polars backend for the dataframe-based lambda functions in augment_expanding_apply (since presumed it will be slower) until we get the series-based lambda functions performing faster.

**Comment by mdancho84** [comment]
Yes I think you are on the right track. 

We should have the column name and function linked so users can add them and control the parameters. 

Something like:

```
("quantile_75", pl_quantile(x, quantile = 0.75))
```

Not technically a lambda function but a function that will spit out a polars function.

**Comment by alexriggio** [comment]
Ah, yeah, that's a nice solution.
