### ISSUE TITLE
More Rolling Augmentors: Rolling, Exponential (EWM), Expanding

### ISSUE THREAD

**Issue by mdancho84** [business-science/pytimetk#65]
- [x] Rolling
- [x] Exponential Weighted
- [x] Expanding

**Comment by tackes** [comment]
should these be separate functions?   or an additional parameter in rolling to choose from?
ie: 
Window_type = ['rolling','expanding']

window_func = ['EWM']

**Comment by mdancho84** [comment]
Yes I'm not sure yet. I need to check out their structure. Right now I'm thinking separate but not sure. 

Working on rolling regression now #66. Should have it finished tonight.

**Comment by JustinKurland** [comment]
I think they should be separate because the params will be slightly different for what each should do. 

- Rolling (I prefer sliding better for a naming convention for this one as it is overlapping but slides not picking up additional data points)
- Tiling (this would be non-overlapping) 
- Growing (This is where the window opens and then continues to get larger as it expands but it uses all the previously occurring data points in the calculation)

**Comment by mdancho84** [comment]
#80 Completes expanding - Needs tests.
